name: Docker Build and Deploy

on:
  push:
    branches:  [main] 

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Logar no DockerHub
      env:
        DOCKER_USERNAME: gianfava
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Construção da imagem Docker
      run: docker build -t gianfava/pokemon:latest .

    - name: Push Docker image
      run: docker push gianfava/pokemon:latest

    - name: Deploy para o Servidor
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 201.23.3.86
        username: aluno
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker pull gianfava/pokemon:latest
          docker stop pokemon || true
          docker rm pokemon || true
          docker run -d --name pokemon -p 8090:80 gianfava/pokemon:latest
